postgres test:
  services:
    - postgres:alpine
      alias:db
  variables:
    # Configure postgres service (https://hub.docker.com/_/postgres/)
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: DnxctEotDlNsk3FuOoVm
  image: denoland/deno:alpine
  before_script:
    # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
    - apk add postgresql
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql -h "db" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f ./db/db-init-scripts/database_init.sql 
    - psql -h "db" -U "postgres" -d "postgres" -c 'SELECT * FROM users;'
  script:
    - cd backend
    - deno test -A --unstable --trace-ops

