stages:
  - build
  - test

variables:
  CI: "true"

frontend_build:
  stage: build
  image: node:19-alpine
  script:
    - cd frontend
    - npm install
    - npm run build

backend_build:
  stage: build
  image: denoland/deno:alpine
  script:
    - cd backend
    - deno task compile

frontend_test:
  stage: test
  image: node:20
  script:
    - cd frontend
    - npm ci
    # - npx playwright install --with-deps
    - npm run check
    - npm run test:unit

# backend_test:
#   stage: test
#   services:
#     - postgres:alpine
#   variables:
#     # Configure postgres service (https://hub.docker.com/_/postgres/)
#     POSTGRES_DB: postgres
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: DnxctEotDlNsk3FuOoVm
#   image: denoland/deno:alpine
#   before_script:
#     # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
#     - apk add postgresql
#     - export PGPASSWORD=$POSTGRES_PASSWORD
#     - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f ./db/db-init-scripts/database_init.sql 
#     - psql -h "postgres" -U "postgres" -d "postgres" -c 'SELECT * FROM users;'
#   script:
#     - cd backend
#     - deno task test
