version: '3.7'
services:
  web:
    image: caddy:2-alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  frontend:
    build: ./frontend
  backend:
    build: ./backend
  # db:
  #   image: postgres:12.1
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"

# volumes:
#   db_data:
