version: '3'
services:
  web:
    image: caddy:2-alpine
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  frontend:
    build: ./frontend
  backend:
    build: ./backend
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5000:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/data/db-init-scripts/:/docker-entrypoint-initdb.d/

volumes:
  data:
