version: '3'
services:
  web:
    image: caddy:2-alpine
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      backend:
        condition: service_healthy
  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy 
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/questions"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: DnxctEotDlNsk3FuOoVm
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/db-init-scripts/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  data: