version: '3'
services:
  web:
    image: caddy:2-alpine
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  frontend:
    build: ./frontend
  backend:
    build: ./backend
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: DnxctEotDlNsk3FuOoVm
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/db-init-scripts/:/docker-entrypoint-initdb.d/

volumes:
  data:
