// TODO: id and password maybe should be optional
// becuase they give me errors in too many places
// since we don't include the password when sending
// the user to the client and instead we send a token
// and the id is automatically generated by the database
// so in some cases we don't have it (yet)
export type User = {
	id: number;
	username: string;
	email: string;
	password: string;
	personality?: string;
};

export type Question = {
	id: number;
	content: string;
	answers: Answer[];
	category_id: number;
};

type Answer = {
	id: number;
	content: string;
};

export type UserAnswer = {
	question_id: number; // Number between 0-34 (or maybe 1-35?)
	answer_id: number; // Number between 0-1 (or maybe 1-2?)
	category_id: number; // Number between 0-6 (or maybe 1-7?)
};
